config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/articles", to:"articles#index"
  get "/articles/new", to:"articles#new"
  get "/articles/:id", to:"articles#show", as: "article"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def create

  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
    @articles = Article.find(params[:id])
  end

  def updated
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%=link_to("create new",articles_new_path)%>
<h1>Wiki NavBar</h1>

<%@articles.each do |article|%>
  <h3><%=link_to(article.title,article_path(article))%></h3>
  <p><%=article.content%></p>
<%end%>

app/views/articles/new.html.erb
<h1>Create a New Post</h1>

<%= form_with model: @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label "Long Description" %>
  <%= f.text_field :long_description %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1><%=@articles.title%></h1>

<div class="container">
  <p><%=@articles.content%></p>
</div>

<div>
  <p><%=@articles.long_description%></p>
</div>

<%=link_to("Home",articles_path)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RrWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>